AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Infrastructure for Visurena Website.
  Creates an S3 bucket for static website hosting, a CloudFront distribution,
  and Route 53 records to point both the apex domain and www subdomain to CloudFront.
  
Parameters:
  DomainName:
    Description: The domain name (e.g., visurena.com)
    Type: String
  HostedZoneId:
    Description: The Route 53 Hosted Zone ID for your domain.
    Type: String
  StackNameSuffix:
    Description: A unique suffix for resource names (to ensure bucket names are unique).
    Type: String
    Default: "visurena"
  ProjectTag:
    Description: A tag value to identify all resources for this project.
    Type: String
    Default: "VisurenaWebsite"
  AcmCertificateArn:
    Description: "The ARN of the ACM certificate for your custom domain (in us-east-1)."
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-${StackNameSuffix}-bucket"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Environment
          Value: Production

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Principal: "*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Set the website endpoint as the origin domain name
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt WebsiteBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Environment
          Value: Production

  DNSRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DNSRecordApex:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  WebsiteBucketName:
    Description: "S3 Bucket name for the website"
    Value: !Ref WebsiteBucket
  CloudFrontDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
