name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Uncomment these steps if your website needs a build process:
      #- name: Set up Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #
      #- name: Build Website
      #  run: |
      #    cd visurena_website
      #    npm install
      #    npm run build
      #    cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Sync Website Files to S3
        run: |
          echo "Syncing contents of the 'visurena_website' folder to S3..."
          aws s3 sync build/ s3://visurena.com-visurena-bucket --delete

